### ISSUE TITLE
compile-fail tests don't seem to work with stable?

### ISSUE THREAD

**Issue by upsuper** [laumann/compiletest-rs#124]
I have the following compile-fail test:
```rust
fn main() {
    x //~ ERROR cannot find value `x` in this scope
}
```

If I use `compiletest_rs = "0.3"` with `cargo +nighly test`, the test passes. However, when I use `compiletest_rs = { version = "0.3", features = ["stable"] }` and plain `cargo test` (on stable channel), the test fails with a the following log:
<details>

```
     Running /Users/upsuper/.cargo-target/debug/deps/compile_tests-0af93046d8980edd

running 1 test

running 1 test

error: failure produced the wrong error: exit code: 101
status: exit code: 101
command: "rustc" "tests/compile-fail/basic.rs" "-L" "/tmp" "--target=x86_64-apple-darwin" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/tmp/basic.stage-id" "-L" "/Users/upsuper/.cargo-target/debug" "-L" "/Users/upsuper/.cargo-target/debug/deps" "-L" "/Users/upsuper/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-L" "/Users/upsuper/.rustup/toolchains/stable-x86_64-apple-darwin/lib" "-L" "/Developer/NVIDIA/CUDA-8.0/lib" "-L" "/usr/local/cuda/lib" "-L" "/tmp/basic.stage-id.aux" "-A" "unused"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
{"message":"cannot find value `x` in this scope","code":{"code":"E0425","explanation":"\nAn unresolved name was used.\n\nErroneous code examples:\n\n```compile_fail,E0425\nsomething_that_doesnt_exist::foo;\n// error: unresolved name `something_that_doesnt_exist::foo`\n\n// or:\n\ntrait Foo {\n    fn bar() {\n        Self; // error: unresolved name `Self`\n    }\n}\n\n// or:\n\nlet x = unknown_variable;  // error: unresolved name `unknown_variable`\n```\n\nPlease verify that the name wasn't misspelled and ensure that the\nidentifier being referred to is valid for the given situation. Example:\n\n```\nenum something_that_does_exist {\n    Foo,\n}\n```\n\nOr:\n\n```\nmod something_that_does_exist {\n    pub static foo : i32 = 0i32;\n}\n\nsomething_that_does_exist::foo; // ok!\n```\n\nOr:\n\n```\nlet unknown_variable = 12u32;\nlet x = unknown_variable; // ok!\n```\n\nIf the item is not defined in the current module, it must be imported using a\n`use` statement, like so:\n\n```\n# mod foo { pub fn bar() {} }\n# fn main() {\nuse foo::bar;\nbar();\n# }\n```\n\nIf the item you are importing is not defined in some super-module of the\ncurrent module, then it must also be declared as public (e.g., `pub fn`).\n"},"level":"error","spans":[{"file_name":"tests/compile-fail/basic.rs","byte_start":16,"byte_end":17,"line_start":2,"line_end":2,"column_start":5,"column_end":6,"is_primary":true,"text":[{"text":"    x //~ ERROR cannot find value `x` in this scope","highlight_start":5,"highlight_end":6}],"label":"not found in this scope","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0425]: cannot find value `x` in this scope\n --> tests/compile-fail/basic.rs:2:5\n  |\n2 |     x //~ ERROR cannot find value `x` in this scope\n  |     ^ not found in this scope\n\n"}
{"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}
{"message":"For more information about this error, try `rustc --explain E0425`.","code":null,"level":"","spans":[],"children":[],"rendered":"For more information about this error, try `rustc --explain E0425`.\n"}

------------------------------------------

thread '[compile-fail] compile-fail/basic.rs' panicked at 'explicit panic', /Users/upsuper/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.14/src/runtest.rs:2550:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test [compile-fail] compile-fail/basic.rs ... FAILED

failures:

failures:
    [compile-fail] compile-fail/basic.rs

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

test compile_tests ... FAILED

failures:

---- compile_tests stdout ----
thread 'compile_tests' panicked at 'Some tests failed', /Users/upsuper/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.14/src/lib.rs:90:22


failures:
    compile_tests

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test compile_tests'
```

</details>

**Comment by laumann** [comment]
We had that discussion recently in #120, specifically [here](https://github.com/laumann/compiletest-rs/pull/120#discussion_r205715461). I think the problem is the same that stable has an exit code of `101` where nightly is `1`.

I think we need to fix #121 and consider how maintainable the `stable` feature really is. For now, don't expect it to work.

**Comment by laumann** [comment]
Has this fixed itself? Is the error code `1` on stable now?

**Comment by upsuper** [comment]
Yeah, it seems to work now. Thanks.
