### ISSUE TITLE
panic if terminal doesn't support color

### ISSUE THREAD

**Issue by jimblandy** [laumann/compiletest-rs#219]
If I do a compiletest test run under Emacs, Emacs sets the `TERM` environment variable to `"dumb"`, and then the test run panics:

```
running 2 tests
test [compile-fail] asynchronous/async-fn-not-unpin.rs ... 
thread '[compile-fail] asynchronous/wrong_mutex.rs' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/tester-0.7.0/src/lib.rs:598:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test [compile-fail] enums/exclusive_range_patterns.rs ... 
...
```
If I change the test command to `TERM=ansi cargo test`, then all is well.

This is the panicking line, in the `tester` crate's `run_test_in_process` function:
```
    monitor_ch.send(message).unwrap();
```
where `monitor_ch` is a `Sender<CompletedTest>`. I'm guessing that whoever is supposed to be receiving on this channel exited early for some color-related reason.

Ideally, if color is not available, one should simply not emit the color escape codes.

**Comment by Munksgaard** [comment]
Hi @jimblandy, thank you for reporting this issue. I'm having trouble recreating it on my local machine. Running `TERM=dumb cargo test` in our test-project doesn't seem to exhibit the error you've described. What project are you running this on? Can you perhaps supply a minimal working example? 

Furthermore, if the panicking line is in the tester crate, I think it would be best to report the error there?

**Comment by jimblandy** [comment]
Here's a test case: https://github.com/jimblandy/compiletest-issue-219

**Comment by jimblandy** [comment]
This is on Fedora.

**Comment by jimblandy** [comment]
Here's a backtrace:
```
thread '[compile-fail] compile-fail/fail.rs' panicked at 'explicit panic', /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.5.0/src/runtest.rs:1091:13
stack backtrace:
   0:     0x5562eeee8594 - backtrace::backtrace::libunwind::trace::hfcd33194db0151d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5562eeee8594 - backtrace::backtrace::trace_unsynchronized::hfd1904bbbd5335b5
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5562eeee8594 - std::sys_common::backtrace::_print_fmt::h8476c57b177b254e
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5562eeee8594 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h73acbc5f6d4b1044
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5562eef1487c - core::fmt::write::hdf236390fbd68d3d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5562eeee4013 - std::io::Write::write_fmt::h5722fa40bb2afafd
                               at src/libstd/io/mod.rs:1532
   6:     0x5562eeeec9e5 - std::sys_common::backtrace::_print::ha468e873aada7c78
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5562eeeec9e5 - std::sys_common::backtrace::print::h149365a2f029de62
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5562eeeec9e5 - std::panicking::default_hook::{{closure}}::hb4a33f9e05934a52
                               at src/libstd/panicking.rs:198
   9:     0x5562eeeec722 - std::panicking::default_hook::hc4535d7b0c743abd
                               at src/libstd/panicking.rs:218
  10:     0x5562eeeed028 - std::panicking::rust_panic_with_hook::haa34a96a6dbd5a2e
                               at src/libstd/panicking.rs:477
  11:     0x5562eebd6909 - std::panicking::begin_panic::hc13db31fda6653e5
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panicking.rs:404
  12:     0x5562eeb522d2 - compiletest_rs::runtest::TestCx::check_expected_errors::hbf784ce80e66c21e
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.5.0/src/runtest.rs:1091
  13:     0x5562eeb43bd2 - compiletest_rs::runtest::TestCx::run_cfail_test::h8774d7f8f841271d
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.5.0/src/runtest.rs:178
  14:     0x5562eeb4376f - compiletest_rs::runtest::TestCx::run_revision::h51a36e526e8fc521
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.5.0/src/runtest.rs:131
  15:     0x5562eeb433c7 - compiletest_rs::runtest::run::hced08a99517d9cc8
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.5.0/src/runtest.rs:83
  16:     0x5562eeace0b3 - compiletest_rs::make_test_closure::{{closure}}::hbbc7ad3b1fdd67a5
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.5.0/src/lib.rs:296
  17:     0x5562eeafc0fe - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8531a16ab487f479
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libcore/ops/function.rs:232
  18:     0x5562eee39f08 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7985dd43c82a4736
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/liballoc/boxed.rs:1034
  19:     0x5562eee723c4 - tester::__rust_begin_short_backtrace::h79b59244a26735d0
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/tester-0.7.0/src/lib.rs:543
  20:     0x5562eee71b23 - tester::run_test::{{closure}}::h41aa525c197d2bff
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/tester-0.7.0/src/lib.rs:527
  21:     0x5562eee48a88 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he27b24d906d641c6
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libcore/ops/function.rs:232
  22:     0x5562eee39f08 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7985dd43c82a4736
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/liballoc/boxed.rs:1034
  23:     0x5562eee0ea24 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h67a735b1515885a6
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panic.rs:318
  24:     0x5562eee046cd - std::panicking::try::do_call::hf044401809b6de96
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panicking.rs:297
  25:     0x5562eee081ed - __rust_try
  26:     0x5562eee0440d - std::panicking::try::ha5ed51b9c6ea18c1
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panicking.rs:274
  27:     0x5562eee0ecc4 - std::panic::catch_unwind::hd1b7f881c25f6bf4
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panic.rs:394
  28:     0x5562eee725eb - tester::run_test_in_process::h2b6f656ca732fdb5
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/tester-0.7.0/src/lib.rs:578
  29:     0x5562eee721ab - tester::run_test::run_test_inner::{{closure}}::h71f34b54acbcbc28
                               at /home/jimb/.cargo/registry/src/github.com-1ecc6299db9ec823/tester-0.7.0/src/lib.rs:474
  30:     0x5562eee33573 - std::sys_common::backtrace::__rust_begin_short_backtrace::h26bd41122981d3ab
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/sys_common/backtrace.rs:130
  31:     0x5562eee03ea4 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h3c656340bdf9035e
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/thread/mod.rs:475
  32:     0x5562eee0ea06 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h3325d5291399e87c
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panic.rs:318
  33:     0x5562eee045b7 - std::panicking::try::do_call::h5c8d01cf221c819b
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panicking.rs:297
  34:     0x5562eee081ed - __rust_try
  35:     0x5562eee04324 - std::panicking::try::h7fa84325c584880c
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panicking.rs:274
  36:     0x5562eee0ed16 - std::panic::catch_unwind::he7c558538e4de63d
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/panic.rs:394
  37:     0x5562eee03c85 - std::thread::Builder::spawn_unchecked::{{closure}}::h02576a4594d83ab5
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libstd/thread/mod.rs:474
  38:     0x5562eee48a5f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5910ae2825b0c87e
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/libcore/ops/function.rs:232
  39:     0x5562eeef476a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha26a994a135d55de
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/liballoc/boxed.rs:1034
  40:     0x5562eeef476a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h677072ad3ba2806b
                               at /rustc/a08c47310c7d49cbdc5d7afb38408ba519967ecd/src/liballoc/boxed.rs:1034
  41:     0x5562eeef476a - std::sys::unix::thread::Thread::new::thread_start::h7c46ce580f54dd0e
                               at src/libstd/sys/unix/thread.rs:87
  42:     0x7fdfcf0b24c0 - start_thread
  43:     0x7fdfcefc6133 - clone
  44:                0x0 - <unknown>
```

**Comment by jimblandy** [comment]
Okay, I filed an issue against the tester crate: https://github.com/messense/rustc-test/issues/6

**Comment by Munksgaard** [comment]
Thank you @jimblandy, that reproduces the issue for me here. I don't have time to look at the issue at the moment, unfortunately, let's hope someone else does.
