### ISSUE TITLE
"every suggestion should have at least one span"

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#86]
On the most recent nightly, 1.23.0-nightly (63739ab7b 2017-11-21), my compile-fail tests started failing with this error. The issue is reproduced as well in the test-project test cases in this repo. Is there a fix we need to grab from upstream?

```
test [compile-fail] compile-fail/asm-gated.rs ... FAILED
test [compile-fail] compile-fail/mut-suggestion.rs ... FAILED
test [compile-fail] compile-fail/multiple-errors.rs ... FAILED
test [compile-fail] compile-fail/trait-bounds-cant-coerce.rs ... FAILED
test [compile-fail] compile-fail/vector-cast-weirdness.rs ... FAILED
test [compile-fail] compile-fail/where-for-self.rs ... FAILED

failures:

---- [compile-fail] compile-fail/asm-gated.rs stdout ----
	thread '[compile-fail] compile-fail/asm-gated.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- [compile-fail] compile-fail/mut-suggestion.rs stdout ----
	thread '[compile-fail] compile-fail/mut-suggestion.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/multiple-errors.rs stdout ----
	thread '[compile-fail] compile-fail/multiple-errors.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/trait-bounds-cant-coerce.rs stdout ----
	thread '[compile-fail] compile-fail/trait-bounds-cant-coerce.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/vector-cast-weirdness.rs stdout ----
	thread '[compile-fail] compile-fail/vector-cast-weirdness.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4

---- [compile-fail] compile-fail/where-for-self.rs stdout ----
	thread '[compile-fail] compile-fail/where-for-self.rs' panicked at 'every suggestion should have at least one span', /checkout/src/libcore/option.rs:874:4
```

**Comment by valff** [comment]
Here is a temporary fix until upstream is merged. Add the following to the `Cargo.toml`.

```toml
[patch.crates-io.compiletest_rs]
git = "https://github.com/valff/compiletest-rs"
```

**Comment by dtolnay** [comment]
Thanks, I can confirm that fixes it.

**Comment by laumann** [comment]
@dtolnay v0.3.2 is out
